# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudokuGUI.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 561)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_0_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_0.sizePolicy().hasHeightForWidth())
        self.btn_0_0.setSizePolicy(sizePolicy)
        self.btn_0_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_0.setObjectName("btn_0_0")
        self.gridLayout.addWidget(self.btn_0_0, 0, 0, 1, 1)
        self.btn_0_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_1.sizePolicy().hasHeightForWidth())
        self.btn_0_1.setSizePolicy(sizePolicy)
        self.btn_0_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_1.setObjectName("btn_0_1")
        self.gridLayout.addWidget(self.btn_0_1, 0, 1, 1, 1)
        self.btn_0_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_2.sizePolicy().hasHeightForWidth())
        self.btn_0_2.setSizePolicy(sizePolicy)
        self.btn_0_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_2.setObjectName("btn_0_2")
        self.gridLayout.addWidget(self.btn_0_2, 0, 2, 1, 1)
        self.btn_0_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_3.sizePolicy().hasHeightForWidth())
        self.btn_0_3.setSizePolicy(sizePolicy)
        self.btn_0_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_3.setObjectName("btn_0_3")
        self.gridLayout.addWidget(self.btn_0_3, 0, 3, 1, 1)
        self.btn_0_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_4.sizePolicy().hasHeightForWidth())
        self.btn_0_4.setSizePolicy(sizePolicy)
        self.btn_0_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_4.setObjectName("btn_0_4")
        self.gridLayout.addWidget(self.btn_0_4, 0, 4, 1, 1)
        self.btn_0_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_5.sizePolicy().hasHeightForWidth())
        self.btn_0_5.setSizePolicy(sizePolicy)
        self.btn_0_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_5.setObjectName("btn_0_5")
        self.gridLayout.addWidget(self.btn_0_5, 0, 5, 1, 1)
        self.btn_0_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_6.sizePolicy().hasHeightForWidth())
        self.btn_0_6.setSizePolicy(sizePolicy)
        self.btn_0_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_6.setObjectName("btn_0_6")
        self.gridLayout.addWidget(self.btn_0_6, 0, 6, 1, 1)
        self.btn_0_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_7.sizePolicy().hasHeightForWidth())
        self.btn_0_7.setSizePolicy(sizePolicy)
        self.btn_0_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_7.setObjectName("btn_0_7")
        self.gridLayout.addWidget(self.btn_0_7, 0, 7, 1, 1)
        self.btn_0_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0_8.sizePolicy().hasHeightForWidth())
        self.btn_0_8.setSizePolicy(sizePolicy)
        self.btn_0_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_0_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_0_8.setObjectName("btn_0_8")
        self.gridLayout.addWidget(self.btn_0_8, 0, 8, 1, 1)
        self.btn_1_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_0.sizePolicy().hasHeightForWidth())
        self.btn_1_0.setSizePolicy(sizePolicy)
        self.btn_1_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_0.setObjectName("btn_1_0")
        self.gridLayout.addWidget(self.btn_1_0, 1, 0, 1, 1)
        self.btn_1_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_1.sizePolicy().hasHeightForWidth())
        self.btn_1_1.setSizePolicy(sizePolicy)
        self.btn_1_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_1.setObjectName("btn_1_1")
        self.gridLayout.addWidget(self.btn_1_1, 1, 1, 1, 1)
        self.btn_1_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_2.sizePolicy().hasHeightForWidth())
        self.btn_1_2.setSizePolicy(sizePolicy)
        self.btn_1_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_2.setObjectName("btn_1_2")
        self.gridLayout.addWidget(self.btn_1_2, 1, 2, 1, 1)
        self.btn_1_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_3.sizePolicy().hasHeightForWidth())
        self.btn_1_3.setSizePolicy(sizePolicy)
        self.btn_1_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_3.setObjectName("btn_1_3")
        self.gridLayout.addWidget(self.btn_1_3, 1, 3, 1, 1)
        self.btn_1_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_4.sizePolicy().hasHeightForWidth())
        self.btn_1_4.setSizePolicy(sizePolicy)
        self.btn_1_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_4.setObjectName("btn_1_4")
        self.gridLayout.addWidget(self.btn_1_4, 1, 4, 1, 1)
        self.btn_1_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_5.sizePolicy().hasHeightForWidth())
        self.btn_1_5.setSizePolicy(sizePolicy)
        self.btn_1_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_5.setObjectName("btn_1_5")
        self.gridLayout.addWidget(self.btn_1_5, 1, 5, 1, 1)
        self.btn_1_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_6.sizePolicy().hasHeightForWidth())
        self.btn_1_6.setSizePolicy(sizePolicy)
        self.btn_1_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_6.setObjectName("btn_1_6")
        self.gridLayout.addWidget(self.btn_1_6, 1, 6, 1, 1)
        self.btn_1_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_7.sizePolicy().hasHeightForWidth())
        self.btn_1_7.setSizePolicy(sizePolicy)
        self.btn_1_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_7.setObjectName("btn_1_7")
        self.gridLayout.addWidget(self.btn_1_7, 1, 7, 1, 1)
        self.btn_1_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1_8.sizePolicy().hasHeightForWidth())
        self.btn_1_8.setSizePolicy(sizePolicy)
        self.btn_1_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_1_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_1_8.setObjectName("btn_1_8")
        self.gridLayout.addWidget(self.btn_1_8, 1, 8, 1, 1)
        self.btn_2_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_0.sizePolicy().hasHeightForWidth())
        self.btn_2_0.setSizePolicy(sizePolicy)
        self.btn_2_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_0.setObjectName("btn_2_0")
        self.gridLayout.addWidget(self.btn_2_0, 2, 0, 1, 1)
        self.btn_2_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_1.sizePolicy().hasHeightForWidth())
        self.btn_2_1.setSizePolicy(sizePolicy)
        self.btn_2_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_1.setObjectName("btn_2_1")
        self.gridLayout.addWidget(self.btn_2_1, 2, 1, 1, 1)
        self.btn_2_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_2.sizePolicy().hasHeightForWidth())
        self.btn_2_2.setSizePolicy(sizePolicy)
        self.btn_2_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_2.setObjectName("btn_2_2")
        self.gridLayout.addWidget(self.btn_2_2, 2, 2, 1, 1)
        self.btn_2_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_3.sizePolicy().hasHeightForWidth())
        self.btn_2_3.setSizePolicy(sizePolicy)
        self.btn_2_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_3.setObjectName("btn_2_3")
        self.gridLayout.addWidget(self.btn_2_3, 2, 3, 1, 1)
        self.btn_2_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_4.sizePolicy().hasHeightForWidth())
        self.btn_2_4.setSizePolicy(sizePolicy)
        self.btn_2_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_4.setObjectName("btn_2_4")
        self.gridLayout.addWidget(self.btn_2_4, 2, 4, 1, 1)
        self.btn_2_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_5.sizePolicy().hasHeightForWidth())
        self.btn_2_5.setSizePolicy(sizePolicy)
        self.btn_2_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_5.setObjectName("btn_2_5")
        self.gridLayout.addWidget(self.btn_2_5, 2, 5, 1, 1)
        self.btn_2_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_6.sizePolicy().hasHeightForWidth())
        self.btn_2_6.setSizePolicy(sizePolicy)
        self.btn_2_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_6.setObjectName("btn_2_6")
        self.gridLayout.addWidget(self.btn_2_6, 2, 6, 1, 1)
        self.btn_2_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_7.sizePolicy().hasHeightForWidth())
        self.btn_2_7.setSizePolicy(sizePolicy)
        self.btn_2_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_7.setObjectName("btn_2_7")
        self.gridLayout.addWidget(self.btn_2_7, 2, 7, 1, 1)
        self.btn_2_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2_8.sizePolicy().hasHeightForWidth())
        self.btn_2_8.setSizePolicy(sizePolicy)
        self.btn_2_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_2_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_2_8.setObjectName("btn_2_8")
        self.gridLayout.addWidget(self.btn_2_8, 2, 8, 1, 1)
        self.btn_3_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_0.sizePolicy().hasHeightForWidth())
        self.btn_3_0.setSizePolicy(sizePolicy)
        self.btn_3_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_0.setObjectName("btn_3_0")
        self.gridLayout.addWidget(self.btn_3_0, 3, 0, 1, 1)
        self.btn_3_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_1.sizePolicy().hasHeightForWidth())
        self.btn_3_1.setSizePolicy(sizePolicy)
        self.btn_3_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_1.setObjectName("btn_3_1")
        self.gridLayout.addWidget(self.btn_3_1, 3, 1, 1, 1)
        self.btn_3_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_2.sizePolicy().hasHeightForWidth())
        self.btn_3_2.setSizePolicy(sizePolicy)
        self.btn_3_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_2.setObjectName("btn_3_2")
        self.gridLayout.addWidget(self.btn_3_2, 3, 2, 1, 1)
        self.btn_3_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_3.sizePolicy().hasHeightForWidth())
        self.btn_3_3.setSizePolicy(sizePolicy)
        self.btn_3_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_3.setObjectName("btn_3_3")
        self.gridLayout.addWidget(self.btn_3_3, 3, 3, 1, 1)
        self.btn_3_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_4.sizePolicy().hasHeightForWidth())
        self.btn_3_4.setSizePolicy(sizePolicy)
        self.btn_3_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_4.setObjectName("btn_3_4")
        self.gridLayout.addWidget(self.btn_3_4, 3, 4, 1, 1)
        self.btn_3_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_5.sizePolicy().hasHeightForWidth())
        self.btn_3_5.setSizePolicy(sizePolicy)
        self.btn_3_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_5.setObjectName("btn_3_5")
        self.gridLayout.addWidget(self.btn_3_5, 3, 5, 1, 1)
        self.btn_3_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_6.sizePolicy().hasHeightForWidth())
        self.btn_3_6.setSizePolicy(sizePolicy)
        self.btn_3_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_6.setObjectName("btn_3_6")
        self.gridLayout.addWidget(self.btn_3_6, 3, 6, 1, 1)
        self.btn_3_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_7.sizePolicy().hasHeightForWidth())
        self.btn_3_7.setSizePolicy(sizePolicy)
        self.btn_3_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_7.setObjectName("btn_3_7")
        self.gridLayout.addWidget(self.btn_3_7, 3, 7, 1, 1)
        self.btn_3_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3_8.sizePolicy().hasHeightForWidth())
        self.btn_3_8.setSizePolicy(sizePolicy)
        self.btn_3_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_3_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_3_8.setObjectName("btn_3_8")
        self.gridLayout.addWidget(self.btn_3_8, 3, 8, 1, 1)
        self.btn_4_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_0.sizePolicy().hasHeightForWidth())
        self.btn_4_0.setSizePolicy(sizePolicy)
        self.btn_4_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_0.setObjectName("btn_4_0")
        self.gridLayout.addWidget(self.btn_4_0, 4, 0, 1, 1)
        self.btn_4_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_1.sizePolicy().hasHeightForWidth())
        self.btn_4_1.setSizePolicy(sizePolicy)
        self.btn_4_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_1.setObjectName("btn_4_1")
        self.gridLayout.addWidget(self.btn_4_1, 4, 1, 1, 1)
        self.btn_4_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_2.sizePolicy().hasHeightForWidth())
        self.btn_4_2.setSizePolicy(sizePolicy)
        self.btn_4_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_2.setObjectName("btn_4_2")
        self.gridLayout.addWidget(self.btn_4_2, 4, 2, 1, 1)
        self.btn_4_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_3.sizePolicy().hasHeightForWidth())
        self.btn_4_3.setSizePolicy(sizePolicy)
        self.btn_4_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_3.setObjectName("btn_4_3")
        self.gridLayout.addWidget(self.btn_4_3, 4, 3, 1, 1)
        self.btn_4_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_4.sizePolicy().hasHeightForWidth())
        self.btn_4_4.setSizePolicy(sizePolicy)
        self.btn_4_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_4.setObjectName("btn_4_4")
        self.gridLayout.addWidget(self.btn_4_4, 4, 4, 1, 1)
        self.btn_4_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_5.sizePolicy().hasHeightForWidth())
        self.btn_4_5.setSizePolicy(sizePolicy)
        self.btn_4_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_5.setObjectName("btn_4_5")
        self.gridLayout.addWidget(self.btn_4_5, 4, 5, 1, 1)
        self.btn_4_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_6.sizePolicy().hasHeightForWidth())
        self.btn_4_6.setSizePolicy(sizePolicy)
        self.btn_4_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_6.setObjectName("btn_4_6")
        self.gridLayout.addWidget(self.btn_4_6, 4, 6, 1, 1)
        self.btn_4_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_7.sizePolicy().hasHeightForWidth())
        self.btn_4_7.setSizePolicy(sizePolicy)
        self.btn_4_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_7.setObjectName("btn_4_7")
        self.gridLayout.addWidget(self.btn_4_7, 4, 7, 1, 1)
        self.btn_4_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4_8.sizePolicy().hasHeightForWidth())
        self.btn_4_8.setSizePolicy(sizePolicy)
        self.btn_4_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_4_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_4_8.setObjectName("btn_4_8")
        self.gridLayout.addWidget(self.btn_4_8, 4, 8, 1, 1)
        self.btn_5_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_0.sizePolicy().hasHeightForWidth())
        self.btn_5_0.setSizePolicy(sizePolicy)
        self.btn_5_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_0.setObjectName("btn_5_0")
        self.gridLayout.addWidget(self.btn_5_0, 5, 0, 1, 1)
        self.btn_5_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_1.sizePolicy().hasHeightForWidth())
        self.btn_5_1.setSizePolicy(sizePolicy)
        self.btn_5_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_1.setObjectName("btn_5_1")
        self.gridLayout.addWidget(self.btn_5_1, 5, 1, 1, 1)
        self.btn_5_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_2.sizePolicy().hasHeightForWidth())
        self.btn_5_2.setSizePolicy(sizePolicy)
        self.btn_5_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_2.setObjectName("btn_5_2")
        self.gridLayout.addWidget(self.btn_5_2, 5, 2, 1, 1)
        self.btn_5_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_3.sizePolicy().hasHeightForWidth())
        self.btn_5_3.setSizePolicy(sizePolicy)
        self.btn_5_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_3.setObjectName("btn_5_3")
        self.gridLayout.addWidget(self.btn_5_3, 5, 3, 1, 1)
        self.btn_5_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_4.sizePolicy().hasHeightForWidth())
        self.btn_5_4.setSizePolicy(sizePolicy)
        self.btn_5_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_4.setObjectName("btn_5_4")
        self.gridLayout.addWidget(self.btn_5_4, 5, 4, 1, 1)
        self.btn_5_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_5.sizePolicy().hasHeightForWidth())
        self.btn_5_5.setSizePolicy(sizePolicy)
        self.btn_5_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_5.setObjectName("btn_5_5")
        self.gridLayout.addWidget(self.btn_5_5, 5, 5, 1, 1)
        self.btn_5_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_6.sizePolicy().hasHeightForWidth())
        self.btn_5_6.setSizePolicy(sizePolicy)
        self.btn_5_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_6.setObjectName("btn_5_6")
        self.gridLayout.addWidget(self.btn_5_6, 5, 6, 1, 1)
        self.btn_5_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_7.sizePolicy().hasHeightForWidth())
        self.btn_5_7.setSizePolicy(sizePolicy)
        self.btn_5_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_7.setObjectName("btn_5_7")
        self.gridLayout.addWidget(self.btn_5_7, 5, 7, 1, 1)
        self.btn_5_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5_8.sizePolicy().hasHeightForWidth())
        self.btn_5_8.setSizePolicy(sizePolicy)
        self.btn_5_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_5_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_5_8.setObjectName("btn_5_8")
        self.gridLayout.addWidget(self.btn_5_8, 5, 8, 1, 1)
        self.btn_6_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_0.sizePolicy().hasHeightForWidth())
        self.btn_6_0.setSizePolicy(sizePolicy)
        self.btn_6_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_0.setObjectName("btn_6_0")
        self.gridLayout.addWidget(self.btn_6_0, 6, 0, 1, 1)
        self.btn_6_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_1.sizePolicy().hasHeightForWidth())
        self.btn_6_1.setSizePolicy(sizePolicy)
        self.btn_6_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_1.setObjectName("btn_6_1")
        self.gridLayout.addWidget(self.btn_6_1, 6, 1, 1, 1)
        self.btn_6_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_2.sizePolicy().hasHeightForWidth())
        self.btn_6_2.setSizePolicy(sizePolicy)
        self.btn_6_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_2.setObjectName("btn_6_2")
        self.gridLayout.addWidget(self.btn_6_2, 6, 2, 1, 1)
        self.btn_6_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_3.sizePolicy().hasHeightForWidth())
        self.btn_6_3.setSizePolicy(sizePolicy)
        self.btn_6_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_3.setObjectName("btn_6_3")
        self.gridLayout.addWidget(self.btn_6_3, 6, 3, 1, 1)
        self.btn_6_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_4.sizePolicy().hasHeightForWidth())
        self.btn_6_4.setSizePolicy(sizePolicy)
        self.btn_6_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_4.setObjectName("btn_6_4")
        self.gridLayout.addWidget(self.btn_6_4, 6, 4, 1, 1)
        self.btn_6_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_5.sizePolicy().hasHeightForWidth())
        self.btn_6_5.setSizePolicy(sizePolicy)
        self.btn_6_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_5.setObjectName("btn_6_5")
        self.gridLayout.addWidget(self.btn_6_5, 6, 5, 1, 1)
        self.btn_6_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_6.sizePolicy().hasHeightForWidth())
        self.btn_6_6.setSizePolicy(sizePolicy)
        self.btn_6_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_6.setObjectName("btn_6_6")
        self.gridLayout.addWidget(self.btn_6_6, 6, 6, 1, 1)
        self.btn_6_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_7.sizePolicy().hasHeightForWidth())
        self.btn_6_7.setSizePolicy(sizePolicy)
        self.btn_6_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_7.setObjectName("btn_6_7")
        self.gridLayout.addWidget(self.btn_6_7, 6, 7, 1, 1)
        self.btn_6_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6_8.sizePolicy().hasHeightForWidth())
        self.btn_6_8.setSizePolicy(sizePolicy)
        self.btn_6_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_6_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_6_8.setObjectName("btn_6_8")
        self.gridLayout.addWidget(self.btn_6_8, 6, 8, 1, 1)
        self.btn_7_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_0.sizePolicy().hasHeightForWidth())
        self.btn_7_0.setSizePolicy(sizePolicy)
        self.btn_7_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_0.setObjectName("btn_7_0")
        self.gridLayout.addWidget(self.btn_7_0, 7, 0, 1, 1)
        self.btn_7_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_1.sizePolicy().hasHeightForWidth())
        self.btn_7_1.setSizePolicy(sizePolicy)
        self.btn_7_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_1.setObjectName("btn_7_1")
        self.gridLayout.addWidget(self.btn_7_1, 7, 1, 1, 1)
        self.btn_7_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_2.sizePolicy().hasHeightForWidth())
        self.btn_7_2.setSizePolicy(sizePolicy)
        self.btn_7_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_2.setObjectName("btn_7_2")
        self.gridLayout.addWidget(self.btn_7_2, 7, 2, 1, 1)
        self.btn_7_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_3.sizePolicy().hasHeightForWidth())
        self.btn_7_3.setSizePolicy(sizePolicy)
        self.btn_7_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_3.setObjectName("btn_7_3")
        self.gridLayout.addWidget(self.btn_7_3, 7, 3, 1, 1)
        self.btn_7_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_4.sizePolicy().hasHeightForWidth())
        self.btn_7_4.setSizePolicy(sizePolicy)
        self.btn_7_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_4.setObjectName("btn_7_4")
        self.gridLayout.addWidget(self.btn_7_4, 7, 4, 1, 1)
        self.btn_7_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_5.sizePolicy().hasHeightForWidth())
        self.btn_7_5.setSizePolicy(sizePolicy)
        self.btn_7_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_5.setObjectName("btn_7_5")
        self.gridLayout.addWidget(self.btn_7_5, 7, 5, 1, 1)
        self.btn_7_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_6.sizePolicy().hasHeightForWidth())
        self.btn_7_6.setSizePolicy(sizePolicy)
        self.btn_7_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_6.setObjectName("btn_7_6")
        self.gridLayout.addWidget(self.btn_7_6, 7, 6, 1, 1)
        self.btn_7_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_7.sizePolicy().hasHeightForWidth())
        self.btn_7_7.setSizePolicy(sizePolicy)
        self.btn_7_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_7.setObjectName("btn_7_7")
        self.gridLayout.addWidget(self.btn_7_7, 7, 7, 1, 1)
        self.btn_7_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7_8.sizePolicy().hasHeightForWidth())
        self.btn_7_8.setSizePolicy(sizePolicy)
        self.btn_7_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_7_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_7_8.setObjectName("btn_7_8")
        self.gridLayout.addWidget(self.btn_7_8, 7, 8, 1, 1)
        self.btn_8_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_0.sizePolicy().hasHeightForWidth())
        self.btn_8_0.setSizePolicy(sizePolicy)
        self.btn_8_0.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_0.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_0.setObjectName("btn_8_0")
        self.gridLayout.addWidget(self.btn_8_0, 8, 0, 1, 1)
        self.btn_8_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_1.sizePolicy().hasHeightForWidth())
        self.btn_8_1.setSizePolicy(sizePolicy)
        self.btn_8_1.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_1.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_1.setObjectName("btn_8_1")
        self.gridLayout.addWidget(self.btn_8_1, 8, 1, 1, 1)
        self.btn_8_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_2.sizePolicy().hasHeightForWidth())
        self.btn_8_2.setSizePolicy(sizePolicy)
        self.btn_8_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_2.setObjectName("btn_8_2")
        self.gridLayout.addWidget(self.btn_8_2, 8, 2, 1, 1)
        self.btn_8_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_3.sizePolicy().hasHeightForWidth())
        self.btn_8_3.setSizePolicy(sizePolicy)
        self.btn_8_3.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_3.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_3.setObjectName("btn_8_3")
        self.gridLayout.addWidget(self.btn_8_3, 8, 3, 1, 1)
        self.btn_8_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_4.sizePolicy().hasHeightForWidth())
        self.btn_8_4.setSizePolicy(sizePolicy)
        self.btn_8_4.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_4.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_4.setObjectName("btn_8_4")
        self.gridLayout.addWidget(self.btn_8_4, 8, 4, 1, 1)
        self.btn_8_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_5.sizePolicy().hasHeightForWidth())
        self.btn_8_5.setSizePolicy(sizePolicy)
        self.btn_8_5.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_5.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_5.setObjectName("btn_8_5")
        self.gridLayout.addWidget(self.btn_8_5, 8, 5, 1, 1)
        self.btn_8_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_6.sizePolicy().hasHeightForWidth())
        self.btn_8_6.setSizePolicy(sizePolicy)
        self.btn_8_6.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_6.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_6.setObjectName("btn_8_6")
        self.gridLayout.addWidget(self.btn_8_6, 8, 6, 1, 1)
        self.btn_8_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_7.sizePolicy().hasHeightForWidth())
        self.btn_8_7.setSizePolicy(sizePolicy)
        self.btn_8_7.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_7.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_7.setObjectName("btn_8_7")
        self.gridLayout.addWidget(self.btn_8_7, 8, 7, 1, 1)
        self.btn_8_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8_8.sizePolicy().hasHeightForWidth())
        self.btn_8_8.setSizePolicy(sizePolicy)
        self.btn_8_8.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_8_8.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_8_8.setObjectName("btn_8_8")
        self.gridLayout.addWidget(self.btn_8_8, 8, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku"))
        self.btn_0_0.setText(_translate("MainWindow", "N/A"))
        self.btn_0_1.setText(_translate("MainWindow", "N/A"))
        self.btn_0_2.setText(_translate("MainWindow", "N/A"))
        self.btn_0_3.setText(_translate("MainWindow", "N/A"))
        self.btn_0_4.setText(_translate("MainWindow", "N/A"))
        self.btn_0_5.setText(_translate("MainWindow", "N/A"))
        self.btn_0_6.setText(_translate("MainWindow", "N/A"))
        self.btn_0_7.setText(_translate("MainWindow", "N/A"))
        self.btn_0_8.setText(_translate("MainWindow", "N/A"))
        self.btn_1_0.setText(_translate("MainWindow", "N/A"))
        self.btn_1_1.setText(_translate("MainWindow", "N/A"))
        self.btn_1_2.setText(_translate("MainWindow", "N/A"))
        self.btn_1_3.setText(_translate("MainWindow", "N/A"))
        self.btn_1_4.setText(_translate("MainWindow", "N/A"))
        self.btn_1_5.setText(_translate("MainWindow", "N/A"))
        self.btn_1_6.setText(_translate("MainWindow", "N/A"))
        self.btn_1_7.setText(_translate("MainWindow", "N/A"))
        self.btn_1_8.setText(_translate("MainWindow", "N/A"))
        self.btn_2_0.setText(_translate("MainWindow", "N/A"))
        self.btn_2_1.setText(_translate("MainWindow", "N/A"))
        self.btn_2_2.setText(_translate("MainWindow", "N/A"))
        self.btn_2_3.setText(_translate("MainWindow", "N/A"))
        self.btn_2_4.setText(_translate("MainWindow", "N/A"))
        self.btn_2_5.setText(_translate("MainWindow", "N/A"))
        self.btn_2_6.setText(_translate("MainWindow", "N/A"))
        self.btn_2_7.setText(_translate("MainWindow", "N/A"))
        self.btn_2_8.setText(_translate("MainWindow", "N/A"))
        self.btn_3_0.setText(_translate("MainWindow", "N/A"))
        self.btn_3_1.setText(_translate("MainWindow", "N/A"))
        self.btn_3_2.setText(_translate("MainWindow", "N/A"))
        self.btn_3_3.setText(_translate("MainWindow", "N/A"))
        self.btn_3_4.setText(_translate("MainWindow", "N/A"))
        self.btn_3_5.setText(_translate("MainWindow", "N/A"))
        self.btn_3_6.setText(_translate("MainWindow", "N/A"))
        self.btn_3_7.setText(_translate("MainWindow", "N/A"))
        self.btn_3_8.setText(_translate("MainWindow", "N/A"))
        self.btn_4_0.setText(_translate("MainWindow", "N/A"))
        self.btn_4_1.setText(_translate("MainWindow", "N/A"))
        self.btn_4_2.setText(_translate("MainWindow", "N/A"))
        self.btn_4_3.setText(_translate("MainWindow", "N/A"))
        self.btn_4_4.setText(_translate("MainWindow", "N/A"))
        self.btn_4_5.setText(_translate("MainWindow", "N/A"))
        self.btn_4_6.setText(_translate("MainWindow", "N/A"))
        self.btn_4_7.setText(_translate("MainWindow", "N/A"))
        self.btn_4_8.setText(_translate("MainWindow", "N/A"))
        self.btn_5_0.setText(_translate("MainWindow", "N/A"))
        self.btn_5_1.setText(_translate("MainWindow", "N/A"))
        self.btn_5_2.setText(_translate("MainWindow", "N/A"))
        self.btn_5_3.setText(_translate("MainWindow", "N/A"))
        self.btn_5_4.setText(_translate("MainWindow", "N/A"))
        self.btn_5_5.setText(_translate("MainWindow", "N/A"))
        self.btn_5_6.setText(_translate("MainWindow", "N/A"))
        self.btn_5_7.setText(_translate("MainWindow", "N/A"))
        self.btn_5_8.setText(_translate("MainWindow", "N/A"))
        self.btn_6_0.setText(_translate("MainWindow", "N/A"))
        self.btn_6_1.setText(_translate("MainWindow", "N/A"))
        self.btn_6_2.setText(_translate("MainWindow", "N/A"))
        self.btn_6_3.setText(_translate("MainWindow", "N/A"))
        self.btn_6_4.setText(_translate("MainWindow", "N/A"))
        self.btn_6_5.setText(_translate("MainWindow", "N/A"))
        self.btn_6_6.setText(_translate("MainWindow", "N/A"))
        self.btn_6_7.setText(_translate("MainWindow", "N/A"))
        self.btn_6_8.setText(_translate("MainWindow", "N/A"))
        self.btn_7_0.setText(_translate("MainWindow", "N/A"))
        self.btn_7_1.setText(_translate("MainWindow", "N/A"))
        self.btn_7_2.setText(_translate("MainWindow", "N/A"))
        self.btn_7_3.setText(_translate("MainWindow", "N/A"))
        self.btn_7_4.setText(_translate("MainWindow", "N/A"))
        self.btn_7_5.setText(_translate("MainWindow", "N/A"))
        self.btn_7_6.setText(_translate("MainWindow", "N/A"))
        self.btn_7_7.setText(_translate("MainWindow", "N/A"))
        self.btn_7_8.setText(_translate("MainWindow", "N/A"))
        self.btn_8_0.setText(_translate("MainWindow", "N/A"))
        self.btn_8_1.setText(_translate("MainWindow", "N/A"))
        self.btn_8_2.setText(_translate("MainWindow", "N/A"))
        self.btn_8_3.setText(_translate("MainWindow", "N/A"))
        self.btn_8_4.setText(_translate("MainWindow", "N/A"))
        self.btn_8_5.setText(_translate("MainWindow", "N/A"))
        self.btn_8_6.setText(_translate("MainWindow", "N/A"))
        self.btn_8_7.setText(_translate("MainWindow", "N/A"))
        self.btn_8_8.setText(_translate("MainWindow", "N/A"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
